# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU03KwDYW_ph8Au8mpI0dUVkcCrRxMtj
"""

import zipfile
with zipfile.ZipFile('/content/drive/MyDrive/KL/vimfd-retrieval.zip', 'r') as z:
    z.extractall('/content/')

!pip install underthesea scikit-learn

import os
os.chdir('/content/vimfd-retrieval')

import config
config.NUM_EPOCHS    = 30
config.BATCH_SIZE_CPU = 64    # Colab T4 dùng batch 64
config.IMAGE_DIR     = '/content/vimfd-retrieval/data/images'
config.PROCESSED_DIR = '/content/vimfd-retrieval/data/processed'

from src.training.train import train
train()



# Cell 7 — Lưu checkpoint về Drive
import shutil
import os

# Tạo thư mục nếu chưa có
os.makedirs('/content/drive/MyDrive/vimfd-retrieval/checkpoints', exist_ok=True)

# Copy checkpoint
shutil.copy(
    '/content/vimfd-retrieval/checkpoints/best.pt',
    '/content/drive/MyDrive/vimfd-retrieval/checkpoints/best.pt'
)
print("Đã lưu checkpoint về Drive!")